import 'dart:convert';
import 'dart:io';

import 'package:yaml/yaml.dart';

/// Build script: reads content/posts/*.md and generates lib/features/posts/data/post_index.dart
///
/// Run:
///   dart run tool/build_posts.dart
///
/// Convention:
/// - Markdown files live under: content/posts/
/// - Each file starts with YAML frontmatter:
///   ---
///   title: ...
///   date: YYYY-MM-DD
///   tags: [a, b]
///   summary: ...
///   ---
///
/// Slug:
/// - By default: filename without extension
void main(List<String> args) {
  final projectRoot = Directory.current.path;

  final postsDir = Directory('$projectRoot/content/posts');
  if (!postsDir.existsSync()) {
    stderr.writeln('Missing directory: ${postsDir.path}');
    exitCode = 2;
    return;
  }

  final mdFiles = postsDir
      .listSync(recursive: false)
      .whereType<File>()
      .where((f) => f.path.endsWith('.md'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final entries = <_PostEntry>[];

  for (final file in mdFiles) {
    final relAssetPath = _toPosixRelative(projectRoot, file.path);

    final text = file.readAsStringSync();
    final fm = _parseFrontMatter(text);

    final slug = _slugFromFilename(file.path);
    final title = (fm['title'] ?? slug).toString().trim();
    final date = (fm['date'] ?? '').toString().trim();

    final tags = _parseTags(fm['tags']);
    final summary = (fm['summary'] ?? '').toString().trim();

    if (date.isEmpty) {
      stderr.writeln('WARNING: Missing date in ${file.path} (expected YYYY-MM-DD)');
    }

    entries.add(
      _PostEntry(
        slug: slug,
        title: title,
        date: date,
        tags: tags,
        summary: summary,
        assetPath: relAssetPath,
      ),
    );
  }

  // Sort newest first (string compare works for YYYY-MM-DD)
  entries.sort((a, b) => b.date.compareTo(a.date));

  final outFile = File(
    '$projectRoot/lib/features/posts/data/post_index.dart',
  );
  outFile.createSync(recursive: true);
  outFile.writeAsStringSync(_renderDart(entries));

  stdout.writeln('Generated: ${_toPosixRelative(projectRoot, outFile.path)}');
  stdout.writeln('Posts: ${entries.length}');
}

class _PostEntry {
  const _PostEntry({
    required this.slug,
    required this.title,
    required this.date,
    required this.tags,
    required this.summary,
    required this.assetPath,
  });

  final String slug;
  final String title;
  final String date;
  final List<String> tags;
  final String summary;
  final String assetPath;
}

Map<String, Object?> _parseFrontMatter(String markdown) {
  // Frontmatter block:
  // ---\n...\n---\n
  final lines = const LineSplitter().convert(markdown);
  if (lines.isEmpty || lines.first.trim() != '---') return const {};

  final end = lines.indexWhere((l) => l.trim() == '---', 1);
  if (end == -1) return const {};

  final yamlText = lines.sublist(1, end).join('\n');
  final doc = loadYaml(yamlText);
  if (doc is! YamlMap) return const {};

  final map = <String, Object?>{};
  for (final e in doc.entries) {
    map[e.key.toString()] = e.value;
  }
  return map;
}

List<String> _parseTags(Object? raw) {
  if (raw == null) return const [];
  if (raw is YamlList) {
    return raw.map((e) => e.toString()).map(_normalizeTag).where((t) => t.isNotEmpty).toList();
  }
  if (raw is List) {
    return raw.map((e) => e.toString()).map(_normalizeTag).where((t) => t.isNotEmpty).toList();
  }
  // allow: "a, b"
  final s = raw.toString();
  return s
      .split(',')
      .map((e) => _normalizeTag(e))
      .where((t) => t.isNotEmpty)
      .toList(growable: false);
}

String _normalizeTag(String t) => t.trim();

String _slugFromFilename(String path) {
  final filename = path.split(Platform.pathSeparator).last;
  return filename.replaceAll(RegExp(r'\.md$'), '');
}

String _toPosixRelative(String root, String absPath) {
  var rel = absPath;
  if (absPath.startsWith(root)) {
    rel = absPath.substring(root.length);
    if (rel.startsWith(Platform.pathSeparator)) {
      rel = rel.substring(1);
    }
  }
  // Flutter assets use POSIX-style paths.
  return rel.replaceAll('\\', '/');
}

String _dartString(String s) {
  // JSON encoder gives us a valid double-quoted string literal.
  return jsonEncode(s);
}

String _renderDart(List<_PostEntry> entries) {
  final b = StringBuffer();

  b.writeln('// GENERATED FILE. DO NOT EDIT.');
  b.writeln('//');
  b.writeln('// Generated by: dart run tool/build_posts.dart');
  b.writeln('// Source: content/posts/*.md');
  b.writeln('');
  b.writeln("import '../domain/post.dart';");
  b.writeln('');
  b.writeln('const posts = <Post>[');

  for (final e in entries) {
    b.writeln('  Post(');
    b.writeln('    slug: ${_dartString(e.slug)},');
    b.writeln('    title: ${_dartString(e.title)},');
    b.writeln('    date: ${_dartString(e.date)},');
    b.writeln('    tags: <String>[${e.tags.map(_dartString).join(', ')}],');
    b.writeln('    summary: ${_dartString(e.summary)},');
    b.writeln('    assetPath: ${_dartString(e.assetPath)},');
    b.writeln('  ),');
  }

  b.writeln('];');
  return b.toString();
}
