// GENERATED FILE. DO NOT EDIT.
//
// Generated by: dart run tool/build_posts.dart
// Source: content/posts/*.md

import '../domain/post.dart';

const posts = <Post>[
  Post(
    slug: "2026-02-13-flutter-web-blog",
    title: "Flutter Web 블로그 시작",
    date: "2026-02-13",
    tags: <String>["flutter", "web", "blog"],
    summary: "Flutter Web + Markdown(Git) 기반으로 블로그 MVP 구조를 잡았다.",
    assetPath: "content/posts/2026-02-13-flutter-web-blog.md",
  ),
  Post(
    slug: "2026-02-10-async-await",
    title: "async/await 정리",
    date: "2026-02-10",
    tags: <String>["dart", "async"],
    summary: "Dart의 Future/async/await를 짧게 정리했다.",
    assetPath: "content/posts/2026-02-10-async-await.md",
  ),
];
